package com.fazakis.mobiletransifexclient;

import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Transifex {
	
	static final String RESPONSE_BAD_AUTH = "Authorization Required";
	static final String RESPONSE_NOT_FOUND = "Not Found";
	static final String RESPONSE_FORBIDEN = "Forbidden";
	static final String RESPONSE_OK = "OK";
	
	static final String REGISTER_URL = "https://www.transifex.com/signup/";
	static final String API_URL = "https://www.transifex.com/api/2/";
	
	public Transifex() {
		// TODO Auto-generated constructor stub
	}
	
	public static String md5(String string) {
	    byte[] hash;

	    try {
	        hash = MessageDigest.getInstance("MD5").digest(string.getBytes("UTF-8"));
	    } catch (NoSuchAlgorithmException e) {
	        throw new RuntimeException("Huh, MD5 should be supported?", e);
	    } catch (UnsupportedEncodingException e) {
	        throw new RuntimeException("Huh, UTF-8 should be supported?", e);
	    }

	    StringBuilder hex = new StringBuilder(hash.length * 2);

	    for (byte b : hash) {
	        int i = (b & 0xFF);
	        if (i < 0x10) hex.append('0');
	        hex.append(Integer.toHexString(i));
	    }

	    return hex.toString();
	}
	
	public static String languageCodeMap(String languageCode){	
		if(languageCode.equals("ach")) return "Acoli";
		else if(languageCode.equals("ady")) return "Adyghe";
		else if(languageCode.equals("af")) return "Afrikaans";
		else if(languageCode.equals("af_ZA")) return "Afrikaans (South Africa)";
		else if(languageCode.equals("ak")) return "Akan";
		else if(languageCode.equals("sq")) return "Albanian";
		else if(languageCode.equals("sq_AL")) return "Albanian (Albania)";
		else if(languageCode.equals("aln")) return "Albanian Gheg";
		else if(languageCode.equals("am")) return "Amharic";
		else if(languageCode.equals("am_ET")) return "Amharic (Ethiopia)";
		else if(languageCode.equals("ar")) return "Arabic";
		else if(languageCode.equals("ar_EG")) return "Arabic (Egypt)";
		else if(languageCode.equals("ar_SA")) return "Arabic (Saudi Arabia)";
		else if(languageCode.equals("ar_SY")) return "Arabic (Syria)";
		else if(languageCode.equals("ar_AA")) return "Arabic (Unitag)";
		else if(languageCode.equals("an")) return "Aragonese";
		else if(languageCode.equals("hy")) return "Armenian";
		else if(languageCode.equals("hy_AM")) return "Armenian (Armenia)";
		else if(languageCode.equals("as")) return "Assamese";
		else if(languageCode.equals("ast")) return "Assamese (India) (as_IN)";
		else if(languageCode.equals("az")) return "Azerbaijani";
		else if(languageCode.equals("az_AZ")) return "Azerbaijani (Azerbaijan)";
		else if(languageCode.equals("bal")) return "Balochi";
		else if(languageCode.equals("eu")) return "Basque";
		else if(languageCode.equals("eu_ES")) return "Basque (Spain)";
		else if(languageCode.equals("be")) return "Belarusian";
		else if(languageCode.equals("be_BY")) return "Belarusian (Belarus)";
		else if(languageCode.equals("be@tarask")) return "Belarusian (Tarask)";
		else if(languageCode.equals("bn")) return "Bengali";
		else if(languageCode.equals("bn_BD")) return "Bengali (Bangladesh)";
		else if(languageCode.equals("bn_IN")) return "Bengali (India)";
		else if(languageCode.equals("brx")) return "Bodo";
		else if(languageCode.equals("bs")) return "Bosnian";
		else if(languageCode.equals("bs_BA")) return "Bosnian (Bosnia and Herzegovina)";
		else if(languageCode.equals("br")) return "Breton";
		else if(languageCode.equals("bg")) return "Bulgarian";
		else if(languageCode.equals("bg_BG")) return "Bulgarian (Bulgaria)";
		else if(languageCode.equals("my")) return "Burmese";
		else if(languageCode.equals("my_MM")) return "Burmese (Myanmar)";
		else if(languageCode.equals("ca")) return "Catalan";
		else if(languageCode.equals("ca_ES")) return "Catalan (Spain)";
		else if(languageCode.equals("ca@valencia")) return "Catalan (Valencian)";
		else if(languageCode.equals("tzm")) return "Central Atlas Tamazight";
		else if(languageCode.equals("hne")) return "Chhattisgarhi";
		else if(languageCode.equals("cgg")) return "Chiga";
		else if(languageCode.equals("zh")) return "Chinese";
		else if(languageCode.equals("zh_CN")) return "Chinese (China)";
		else if(languageCode.equals("zh_CN.GB2312")) return "Chinese (China) (GB2312)";
		else if(languageCode.equals("gan")) return "Chinese (Gan)";
		else if(languageCode.equals("hak")) return "Chinese (Hakka)";
		else if(languageCode.equals("zh_HK")) return "Chinese (Hong Kong)";
		else if(languageCode.equals("czh")) return "Chinese (Huizhou)";
		else if(languageCode.equals("cjy")) return "Chinese (Jinyu)";
		else if(languageCode.equals("lzh")) return "Chinese (Literary)";
		else if(languageCode.equals("cmn")) return "Chinese (Mandarin)";
		else if(languageCode.equals("mnp")) return "Chinese (Min Bei)";
		else if(languageCode.equals("cdo")) return "Chinese (Min Dong)";
		else if(languageCode.equals("nan")) return "Chinese (Min Nan)";
		else if(languageCode.equals("czo")) return "Chinese (Min Zhong)";
		else if(languageCode.equals("cpx")) return "Chinese (Pu-Xian)";
		else if(languageCode.equals("zh_TW")) return "Chinese (Taiwan)";
		else if(languageCode.equals("zh_TW.Big5")) return "Chinese (Taiwan) (Big5)";
		else if(languageCode.equals("wuu")) return "Chinese (Wu)";
		else if(languageCode.equals("hsn")) return "Chinese (Xiang)";
		else if(languageCode.equals("yue")) return "Chinese (Yue)";
		else if(languageCode.equals("cv")) return "Chuvash";
		else if(languageCode.equals("kw")) return "Cornish";
		else if(languageCode.equals("co")) return "Corsican";
		else if(languageCode.equals("crh")) return "Crimean Turkish";
		else if(languageCode.equals("hr")) return "Croatian";
		else if(languageCode.equals("hr_HR")) return "Croatian (Croatia)";
		else if(languageCode.equals("cs")) return "Czech";
		else if(languageCode.equals("cs_CZ")) return "Czech (Czech Republic)";
		else if(languageCode.equals("da")) return "Danish";
		else if(languageCode.equals("da_DK")) return "Danish (Denmark)";
		else if(languageCode.equals("dv")) return "Divehi";
		else if(languageCode.equals("nl")) return "Dutch";
		else if(languageCode.equals("nl_BE")) return "Dutch (Belgium)";
		else if(languageCode.equals("nl_NL")) return "Dutch (Netherlands)";
		else if(languageCode.equals("dz")) return "Dzongkha";
		else if(languageCode.equals("dz_BT")) return "Dzongkha (Bhutan)";
		else if(languageCode.equals("en")) return "English";
		else if(languageCode.equals("en_AU")) return "English (Australia)";
		else if(languageCode.equals("en_CA")) return "English (Canada)";
		else if(languageCode.equals("en_IE")) return "English (Ireland)";
		else if(languageCode.equals("en_ZA")) return "English (South Africa)";
		else if(languageCode.equals("en_GB")) return "English (United Kingdom)";
		else if(languageCode.equals("en_US")) return "English (United States)";
		else if(languageCode.equals("myv")) return "Erzya";
		else if(languageCode.equals("eo")) return "Esperanto";
		else if(languageCode.equals("et")) return "Estonian";
		else if(languageCode.equals("et_EE")) return "Estonian (Estonia)";
		else if(languageCode.equals("fo")) return "Faroese";
		else if(languageCode.equals("fo_FO")) return "Faroese (Faroe Islands)";
		else if(languageCode.equals("fil")) return "Filipino";
		else if(languageCode.equals("fi")) return "Finnish";
		else if(languageCode.equals("fi_FI")) return "Finnish (Finland)";
		else if(languageCode.equals("frp")) return "Franco-Provençal (Arpitan)";
		else if(languageCode.equals("fr")) return "French";
		else if(languageCode.equals("fr_CA")) return "French (Canada)";
		else if(languageCode.equals("fr_FR")) return "French (France)";
		else if(languageCode.equals("fr_CH")) return "French (Switzerland)";
		else if(languageCode.equals("ff")) return "Friulian (fur)Fulah";
		else if(languageCode.equals("ff_SN")) return "Fulah (Senegal)";
		else if(languageCode.equals("gd")) return "Gaelic, Scottish";
		else if(languageCode.equals("gl")) return "Galician";
		else if(languageCode.equals("gl_ES")) return "Galician (Spain)";
		else if(languageCode.equals("lg")) return "Ganda";
		else if(languageCode.equals("ka")) return "Georgian";
		else if(languageCode.equals("ka_GE")) return "Georgian (Georgia)";
		else if(languageCode.equals("de")) return "German";
		else if(languageCode.equals("de_AT")) return "German (Austria)";
		else if(languageCode.equals("de_DE")) return "German (Germany)";
		else if(languageCode.equals("de_CH")) return "German (Switzerland)";
		else if(languageCode.equals("el")) return "Greek";
		else if(languageCode.equals("el_GR")) return "Greek (Greece)";
		else if(languageCode.equals("gu")) return "Gujarati";
		else if(languageCode.equals("gu_IN")) return "Gujarati (India)";
		else if(languageCode.equals("gun")) return "Gun";
		else if(languageCode.equals("ht")) return "Haitian (Haitian Creole)";
		else if(languageCode.equals("ht_HT")) return "Haitian (Haitian Creole) (Haiti)";
		else if(languageCode.equals("")) return "Hausa";
		else if(languageCode.equals("he")) return "Hebrew";
		else if(languageCode.equals("he_IL")) return "Hebrew (Israel)";
		else if(languageCode.equals("hi")) return "Hindi";
		else if(languageCode.equals("hi_IN")) return "Hindi (India)";
		else if(languageCode.equals("hu")) return "Hungarian";
		else if(languageCode.equals("hu_HU")) return "Hungarian (Hungary)";
		else if(languageCode.equals("is")) return "Icelandic";
		else if(languageCode.equals("is_IS")) return "Icelandic (Iceland)";
		else if(languageCode.equals("ig")) return "Igbo";
		else if(languageCode.equals("ilo")) return "Iloko";
		else if(languageCode.equals("id")) return "Indonesian";
		else if(languageCode.equals("id_ID")) return "Indonesian (Indonesia)";
		else if(languageCode.equals("ia")) return "Interlingua";
		else if(languageCode.equals("ga")) return "Irish";
		else if(languageCode.equals("ga_IE")) return "Irish (Ireland)";
		else if(languageCode.equals("it")) return "Italian";
		else if(languageCode.equals("it_IT")) return "Italian (Italy)";
		else if(languageCode.equals("ja")) return "Japanese";
		else if(languageCode.equals("ja_JP")) return "Japanese (Japan)";
		else if(languageCode.equals("jv")) return "Javanese";
		else if(languageCode.equals("kab")) return "Kabyle";
		else if(languageCode.equals("kn")) return "Kannada";
		else if(languageCode.equals("kn_IN")) return "Kannada (India)";
		else if(languageCode.equals("pam")) return "Kapampangan";
		else if(languageCode.equals("ks")) return "Kashmiri";
		else if(languageCode.equals("ks_IN")) return "Kashmiri (India)";
		else if(languageCode.equals("csb")) return "Kashubian";
		else if(languageCode.equals("kk")) return "Kazakh";
		else if(languageCode.equals("kk_KZ")) return "Kazakh (Kazakhstan)";
		else if(languageCode.equals("km")) return "Khmer";
		else if(languageCode.equals("km_KH")) return "Khmer (Cambodia)";
		else if(languageCode.equals("rw")) return "Kinyarwanda";
		else if(languageCode.equals("ky")) return "Kirgyz";
		else if(languageCode.equals("tlh")) return "Klingon";
		else if(languageCode.equals("ko")) return "Korean";
		else if(languageCode.equals("ko_KR")) return "Korean (Korea)";
		else if(languageCode.equals("ku")) return "Kurdish";
		else if(languageCode.equals("ku_IQ")) return "Kurdish (Iraq)";
		else if(languageCode.equals("lo")) return "Lao";
		else if(languageCode.equals("lo_LA")) return "Lao (Laos)";
		else if(languageCode.equals("la")) return "Latin";
		else if(languageCode.equals("lv")) return "Latvian";
		else if(languageCode.equals("lv_LV")) return "Latvian (Latvia)";
		else if(languageCode.equals("lij")) return "Ligurian";
		else if(languageCode.equals("li")) return "Limburgian";
		else if(languageCode.equals("ln")) return "Lingala";
		else if(languageCode.equals("lt")) return "Lithuanian";
		else if(languageCode.equals("lt_LT")) return "Lithuanian (Lithuania)";
		else if(languageCode.equals("en@lolcat")) return "LOLCAT English";
		else if(languageCode.equals("nds")) return "Low German";
		else if(languageCode.equals("lb")) return "Luxembourgish";
		else if(languageCode.equals("mk")) return "Macedonian";
		else if(languageCode.equals("mk_MK")) return "Macedonian (Macedonia)";
		else if(languageCode.equals("mai")) return "Maithili";
		else if(languageCode.equals("mg")) return "Malagasy";
		else if(languageCode.equals("ms")) return "Malay";
		else if(languageCode.equals("ml")) return "Malayalam";
		else if(languageCode.equals("ml_IN")) return "Malayalam (India)";
		else if(languageCode.equals("ms_MY")) return "Malay (Malaysia)";
		else if(languageCode.equals("mt")) return "Maltese";
		else if(languageCode.equals("mt_MT")) return "Maltese (Malta)";
		else if(languageCode.equals("mi")) return "Maori";
		else if(languageCode.equals("arn")) return "Mapudungun";
		else if(languageCode.equals("mr")) return "Marathi";
		else if(languageCode.equals("mr_IN")) return "Marathi (India)";
		else if(languageCode.equals("mw1")) return "Mirandese";
		else if(languageCode.equals("mn")) return "Mongolian";
		else if(languageCode.equals("mn_MN")) return "Mongolian (Mongolia)";
		else if(languageCode.equals("nah")) return "Nahuatl";
		else if(languageCode.equals("nr")) return "Ndebele, South";
		else if(languageCode.equals("nap")) return "Neapolitan";
		else if(languageCode.equals("ne")) return "Nepali";
		else if(languageCode.equals("ne_NP")) return "Nepali (Nepal)";
		else if(languageCode.equals("nqo")) return "Nias (nia)N'ko";
		else if(languageCode.equals("se")) return "Northern Sami";
		else if(languageCode.equals("nso")) return "Northern Sotho";
		else if(languageCode.equals("no")) return "Norwegian";
		else if(languageCode.equals("nb")) return "Norwegian Bokmål";
		else if(languageCode.equals("nb_NO")) return "Norwegian Bokmål (Norway)";
		else if(languageCode.equals("no_NO")) return "Norwegian (Norway)";
		else if(languageCode.equals("nn")) return "Norwegian Nynorsk";
		else if(languageCode.equals("nn_NO")) return "Norwegian Nynorsk (Norway)";
		else if(languageCode.equals("oc")) return "Nyanja (ny)Occitan (post 1500)";
		else if(languageCode.equals("or")) return "Oriya";
		else if(languageCode.equals("or_IN")) return "Oriya (India)";
		else if(languageCode.equals("om")) return "Oromo";
		else if(languageCode.equals("os")) return "Ossetic";
		else if(languageCode.equals("pfl")) return "Palatinate German";
		else if(languageCode.equals("pa")) return "Panjabi (Punjabi)";
		else if(languageCode.equals("pa_IN")) return "Panjabi (Punjabi) (India)";
		else if(languageCode.equals("pap")) return "Papiamento";
		else if(languageCode.equals("fa_IR")) return "Persian (fa)Persian (Iran)";
		else if(languageCode.equals("pms")) return "Piemontese";
		else if(languageCode.equals("en@pirate")) return "Pirate English";
		else if(languageCode.equals("pl")) return "Polish";
		else if(languageCode.equals("pl_PL")) return "Polish (Poland)";
		else if(languageCode.equals("pt")) return "Portuguese";
		else if(languageCode.equals("pt_BR")) return "Portuguese (Brazil)";
		else if(languageCode.equals("pt_PT")) return "Portuguese (Portugal)";
		else if(languageCode.equals("ps")) return "Pushto";
		else if(languageCode.equals("ro")) return "Romanian";
		else if(languageCode.equals("ro_RO")) return "Romanian (Romania)";
		else if(languageCode.equals("rm")) return "Romansh";
		else if(languageCode.equals("ru")) return "Russian";
		else if(languageCode.equals("ru@petr1708")) return "Russian Petrine orthography";
		else if(languageCode.equals("ru_RU")) return "Russian (Russia)";
		else if(languageCode.equals("sah")) return "Sakha (Yakut)";
		else if(languageCode.equals("sm")) return "Samoan";
		else if(languageCode.equals("sc")) return "Sardinian";
		else if(languageCode.equals("sco")) return "Scots";
		else if(languageCode.equals("sr")) return "Serbian";
		else if(languageCode.equals("sr@latin")) return "Serbian (Latin)";
		else if(languageCode.equals("sr_RS@latin")) return "Serbian (Latin) (Serbia)";
		else if(languageCode.equals("sr_RS")) return "Serbian (Serbia)";
		else if(languageCode.equals("szl")) return "Shona (sn)Silesian";
		else if(languageCode.equals("si")) return "Sindhi (sd)Sinhala";
		else if(languageCode.equals("si_LK")) return "Sinhala (Sri Lanka)";
		else if(languageCode.equals("sk")) return "Slovak";
		else if(languageCode.equals("sk_SK")) return "Slovak (Slovakia)";
		else if(languageCode.equals("sl")) return "Slovenian";
		else if(languageCode.equals("sl_SI")) return "Slovenian (Slovenia)";
		else if(languageCode.equals("so")) return "Somali";
		else if(languageCode.equals("son")) return "Songhay";
		else if(languageCode.equals("st")) return "Sotho, Southern";
		else if(languageCode.equals("st_ZA")) return "Sotho, Southern (South Africa)";
		else if(languageCode.equals("sma")) return "Southern Sami";
		else if(languageCode.equals("es")) return "Spanish";
		else if(languageCode.equals("es_AR")) return "Spanish (Argentina)";
		else if(languageCode.equals("es_BO")) return "Spanish (Bolivia)";
		else if(languageCode.equals("es_CL")) return "Spanish (Chile)";
		else if(languageCode.equals("es_CO")) return "Spanish (Colombia)";
		else if(languageCode.equals("es_CR")) return "Spanish (Costa Rica)";
		else if(languageCode.equals("es_DO")) return "Spanish (Dominican Republic)";
		else if(languageCode.equals("es_EC")) return "Spanish (Ecuador)";
		else if(languageCode.equals("es_SV")) return "Spanish (El Salvador)";
		else if(languageCode.equals("es_419")) return "Spanish (Latin America)";
		else if(languageCode.equals("es_MX")) return "Spanish (Mexico)";
		else if(languageCode.equals("es_NI")) return "Spanish (Nicaragua)";
		else if(languageCode.equals("es_PA")) return "Spanish (Panama)";
		else if(languageCode.equals("es_PY")) return "Spanish (Paraguay)";
		else if(languageCode.equals("es_PE")) return "Spanish (Peru)";
		else if(languageCode.equals("es_PR")) return "Spanish (Puerto Rico)";
		else if(languageCode.equals("es_ES")) return "Spanish (Spain)";
		else if(languageCode.equals("es_UY")) return "Spanish (Uruguay)";
		else if(languageCode.equals("es_VE")) return "Spanish (Venezuela)";
		else if(languageCode.equals("su")) return "Sundanese";
		else if(languageCode.equals("sw")) return "Swahili";
		else if(languageCode.equals("sw_KE")) return "Swahili (Kenya)";
		else if(languageCode.equals("ss")) return "Swati";
		else if(languageCode.equals("sv")) return "Swedish";
		else if(languageCode.equals("sv_FI")) return "Swedish (Finland)";
		else if(languageCode.equals("sv_SE")) return "Swedish (Sweden)";
		else if(languageCode.equals("tl")) return "Tagalog";
		else if(languageCode.equals("tl_PH")) return "Tagalog (Philippines)";
		else if(languageCode.equals("tg")) return "Tajik";
		else if(languageCode.equals("tg_TJ")) return "Tajik (Tajikistan)";
		else if(languageCode.equals("ta")) return "Tamil";
		else if(languageCode.equals("ta_IN")) return "Tamil (India)";
		else if(languageCode.equals("ta_LK")) return "Tamil (Sri-Lanka)";
		else if(languageCode.equals("tt")) return "Tatar";
		else if(languageCode.equals("te")) return "Telugu";
		else if(languageCode.equals("te_IN")) return "Telugu (India)";
		else if(languageCode.equals("tet")) return "Tetum (Tetun)";
		else if(languageCode.equals("th")) return "Thai";
		else if(languageCode.equals("th_TH")) return "Thai (Thailand)";
		else if(languageCode.equals("bo")) return "Tibetan";
		else if(languageCode.equals("bo_CN")) return "Tibetan (China)";
		else if(languageCode.equals("ti")) return "Tigrinya";
		else if(languageCode.equals("to")) return "Tongan";
		else if(languageCode.equals("ts")) return "Tsonga";
		else if(languageCode.equals("tn")) return "Tswana";
		else if(languageCode.equals("tr")) return "Turkish";
		else if(languageCode.equals("tr_TR")) return "Turkish (Turkey)";
		else if(languageCode.equals("tk")) return "Turkmen";
		else if(languageCode.equals("tk_TM")) return "Turkmen (Turkmenistan)";
		else if(languageCode.equals("udm")) return "Udmurt";
		else if(languageCode.equals("ug")) return "Uighur";
		else if(languageCode.equals("ug@Latin")) return "Uighur (Latin script)";
		else if(languageCode.equals("uk")) return "Ukrainian";
		else if(languageCode.equals("uk_UA")) return "Ukrainian (Ukraine)";
		else if(languageCode.equals("hsb")) return "Upper Sorbian";
		else if(languageCode.equals("ur")) return "Urdu";
		else if(languageCode.equals("ur_PK")) return "Urdu (Pakistan)";
		else if(languageCode.equals("uz")) return "Uzbek";
		else if(languageCode.equals("ve")) return "Venda";
		else if(languageCode.equals("vec")) return "Venetian";
		else if(languageCode.equals("vi")) return "Vietnamese";
		else if(languageCode.equals("vi_VN")) return "Vietnamese (Viet Nam)";
		else if(languageCode.equals("vls")) return "Vlaams";
		else if(languageCode.equals("wa")) return "Walloon";
		else if(languageCode.equals("war")) return "Wáray-Wáray";
		else if(languageCode.equals("cy")) return "Welsh";
		else if(languageCode.equals("cy_GB")) return "Welsh (United Kingdom)";
		else if(languageCode.equals("fy")) return "Western Frisian";
		else if(languageCode.equals("fy_NL")) return "Western Frisian (Netherlands)";
		else if(languageCode.equals("wo")) return "Wolof";
		else if(languageCode.equals("wo_SN")) return "Wolof (Senegal)";
		else if(languageCode.equals("xh")) return "Xhosa";
		else if(languageCode.equals("yi")) return "Yiddish";
		else if(languageCode.equals("yo")) return "Yoruba";
		else if(languageCode.equals("zu")) return "Zulu";
		else if(languageCode.equals("zu_ZA")) return "Zulu (South Africa)";
		else
			return languageCode;
	}

}
